# Generated by Django 5.0.6 on 2024-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='summary',
            new_name='summary_supervised',
        ),
        migrations.AddField(
            model_name='document',
            name='summary_unsupervised',
            field=models.TextField(blank=True, null=True),
        ),
    ]
