# Generated by Django 5.0.6 on 2024-07-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_summary_document_summary_supervised_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='document',
            name='summary_t5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
