# Generated by Django 5.0.6 on 2024-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_document_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary_sumy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
